### PR TITLE
fix: use hashbang and execute directly

### PR DESCRIPTION
**Pull request by guyfedwards**

### CODE REVIEW

**Comment by benswinburne** [comment]
It already tells you the error and why...

```
#!/bin/bash -eo pipefail
node import
Found 311 total emoji on 1 pages
Attempting to upload 1 emoji to flat15

error on joy: error_name_taken

requests: 1 
successes: 0 
errors: 1
Exited with code 1
```

**Comment by guyfedwards** [comment]
Weird, I thought it did but then I came across this: 
screenshot 2019-02-12 15 19 41

https://circleci.com/gh/guyfedwards/emoji/131

**Comment by benswinburne** [comment]
Ah it looks like it doesn't report the errors after the first failure. if you look at circleci.com/gh/guyfedwards/emoji/130 where `:joy:` failed then the error is there.

Perhaps make this PR report the reason as well as just the name then the behaviour will be consistent across all builds.

**Comment by guyfedwards** [comment]
Nah i've just removed it as I don't want to show multiple error messages and we should be mitigating this issue in emojo soon anyway

**Review by benswinburne — APPROVED** [review]

**Pull request merged**
